<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/8/4
 * Time: 15:08
 */

namespace app\index\controller;
use think\Controller;
use app\index\model\Cate;
class Base extends Controller{

    public function _initialize() {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //顶级分类
        $topCate = Cate::getTopCate();
        //一级分类
        $firCate = Cate::getFirCate();

        //$arr = Cate::getCate();
        //dump($arr);exit;
        $this->assign([
            'topCate'=>$topCate,
            'firCate'=>$firCate,
        ]);
    }

    /**
     *
     * 检测前台会员是否登录
     */

    public function isLogin(){
        $index = session('index');
        if(!empty($index)){
            return $index;
        }else{
            return false;
        }
    }


/*    public function _empty(){
        $this->error('非法访问');
    }*/

}